server:
  port: 8888
kline:
  binance:
    spot:
      minMaintainCount: 2000
      listenIntervals:
        - 1h
        - 1d
      listenSymbolPatterns:
        - .*?USDT
    future:
      minMaintainCount: 2000
      listenIntervals:
        - 1h
        - 1d
      listenSymbolPatterns:
        - .*?USDT
