server:
  port: 8888
kline:
  binance:
    spot:
      enabled: false
      minMaintainCount: 2000
      listenIntervals:
        - 1h
        - 1d
    future:
      minMaintainCount: 2000
      listenIntervals:
        - 1h
        - 1d
