server:
  port: 1888
number:
  type: double
kline:
  binance:
    spot:
      minMaintainCount: 2000
      listenIntervals:
        - 1h
        - 1d
      listenSymbolPatterns:
        - .*?USDT
    future:
      minMaintainCount: 2000
      listenIntervals:
        - 1h
        - 1d
      listenSymbolPatterns:
        - .*?USDT

client:
  binanceSpot:
    api:
      rootUrl: https://api.binance.com
  binanceFuture:
    api:
      rootUrl: https://fapi.binance.com

ws:
  client:
    binanceSpot:
      url: wss://stream.binance.com/ws
    binanceFuture:
      url: wss://fstream.binance.com/ws